## Put comments here that give an overall description of what your
## functions do

## This function converts a invertible matrix into 'special matrix', i.e. a list
## containing methods used to access the matrix and cache its inverse

makeCacheMatrix <- function(x = matrix()) {
    inv = NULL
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    
    get <- function() x
    setinverse <- function(imatrix) inv <<- imatrix
    getinverse <- function() inv
    list(set = set, get = get,
         setinverse = setinverse,
         getinverse = getinverse)
}


## This function takes the list generated by makeCacheMatrix and gives the inverse
## of supplied matrix from cache if already computed, else by calculating if first time

cacheSolve <- function(x, ...) {
    
    ## Return a matrix that is the inverse of 'x'
    
    inv <- x$getinverse()
    if(!is.null(inv)) {
        message("getting cached data")
            return(inv)
    }
    
    matrix <- x$get()
    inv <- solve(matrix)
    x$setinverse(inv)
    inv
}
